"""Memory-mapped Stage-1 CTE latent cache reader.

This module reads the cache generated by ``scripts/precompute_zeva_cte_latents.py``.
Latents are stored as the raw uint16 bit-pattern of torch.bfloat16 values so
loading does not introduce a numerical conversion.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import torch
from torch.utils.data import Dataset

from fastwam.datasets.zeva_robotwin_dataset import EpisodeMetadata
from fastwam.zeva.stage1_sampling import CTETrainIndex


CACHE_FORMAT = "zeva_cte_window_latent_cache_v1"
CACHE_FORMAT_ALIASES = {
    CACHE_FORMAT,
    "zeva_cte_latent_cache_v1",
}
LATENT_STORAGE_DTYPE = "bfloat16_bits_u16"


def bf16_tensor_to_u16_numpy(value: torch.Tensor) -> np.ndarray:
    """Return a CPU uint16 ndarray containing the exact BF16 bit-pattern."""
    tensor = value.detach().to(device="cpu", dtype=torch.bfloat16).contiguous()
    return tensor.view(torch.uint16).numpy().copy()


def u16_numpy_to_bf16_tensor(value: np.ndarray) -> torch.Tensor:
    """Reinterpret a uint16 ndarray as BF16 without numerical conversion."""
    array = np.asarray(value, dtype=np.uint16)
    # np.memmap slices can be non-owning; copy so DataLoader workers never
    # retain the whole mmap through a strided/non-writeable view.
    bits = torch.from_numpy(np.array(array, copy=True, dtype=np.uint16))
    return bits.view(torch.bfloat16)


class CachedCTELatentWindowDataset(Dataset):
    """Sparse Dataset indexed by the original RoboTwin ``dataset_index``.

    The training sampler stores original source indices (0..~6M), therefore
    ``__getitem__`` intentionally accepts those sparse source indices rather
    than 0..len(cache)-1 ordinal positions.
    """

    def __init__(
        self,
        root: str | Path,
        *,
        expected_dataset_stats_sha256: str | None = None,
        expected_semantic_task_sha256: str | None = None,
        expected_video_size: tuple[int, int] | list[int] | None = None,
        expected_action_dim: int | None = None,
        expected_transition_steps: int | None = None,
        expected_latent_channels: int | None = None,
    ) -> None:
        self.root = Path(root).expanduser().resolve()
        manifest_path = self.root / "manifest.json"
        index_path = self.root / "index.json"
        if not manifest_path.is_file() or not index_path.is_file():
            raise FileNotFoundError(
                f"incomplete CTE latent cache: expected {manifest_path} and {index_path}"
            )

        self.manifest: dict[str, Any] = json.loads(manifest_path.read_text(encoding="utf-8"))
        self.rows: list[dict[str, Any]] = json.loads(index_path.read_text(encoding="utf-8"))

        actual_format = str(self.manifest.get("format"))
        if actual_format not in CACHE_FORMAT_ALIASES:
            raise ValueError(
                f"unsupported latent cache format: {actual_format!r}; "
                f"expected one of {sorted(CACHE_FORMAT_ALIASES)!r}"
            )
        if str(self.manifest.get("latent_storage_dtype")) != LATENT_STORAGE_DTYPE:
            raise ValueError(
                "latent cache storage mismatch: "
                f"{self.manifest.get('latent_storage_dtype')!r}"
            )
        if int(self.manifest.get("num_windows", -1)) != len(self.rows):
            raise ValueError(
                "latent cache manifest/index count mismatch: "
                f"manifest={self.manifest.get('num_windows')}, index={len(self.rows)}"
            )

        self.latent_shape = tuple(int(v) for v in self.manifest["latent_shape"])
        self.cte_vae_input_size = tuple(int(v) for v in self.manifest["cte_vae_input_size"])
        self.vae_metadata = dict(self.manifest.get("vae_metadata", {}))
        self.semantic_task_identity = dict(self.manifest.get("semantic_task_identity", {}))

        if len(self.latent_shape) != 4:
            raise ValueError(
                f"latent_shape must be [T,C,H,W], got {self.latent_shape}"
            )
        if self.latent_shape[0] != 9:
            raise ValueError(
                f"RoboTwin Stage-1 cache requires 9 latent boundaries/window, got {self.latent_shape[0]}"
            )
        if len(self.cte_vae_input_size) != 2 or min(self.cte_vae_input_size) < 1:
            raise ValueError(
                f"cte_vae_input_size must be [H,W], got {self.cte_vae_input_size}"
            )
        latent_channels = int(self.manifest.get("latent_channels", -1))
        if latent_channels != self.latent_shape[1]:
            raise ValueError(
                "latent cache channel metadata mismatch: "
                f"latent_channels={latent_channels}, latent_shape={self.latent_shape}"
            )
        if min(self.latent_shape) < 1:
            raise ValueError(f"latent_shape must contain positive dimensions, got {self.latent_shape}")


        def _expect(name: str, actual: Any, expected: Any) -> None:
            if expected is not None and actual != expected:
                raise ValueError(
                    f"latent cache identity mismatch for {name}: "
                    f"expected={expected!r}, actual={actual!r}"
                )

        _expect(
            "dataset_stats_sha256",
            str(self.manifest.get("dataset_stats_sha256")),
            None if expected_dataset_stats_sha256 is None else str(expected_dataset_stats_sha256),
        )
        _expect(
            "semantic_task_map_sha256",
            str(self.manifest.get("semantic_task_map_sha256")),
            None if expected_semantic_task_sha256 is None else str(expected_semantic_task_sha256),
        )
        if expected_video_size is not None:
            _expect("video_size", tuple(int(v) for v in self.manifest["video_size"]), tuple(int(v) for v in expected_video_size))
        if expected_action_dim is not None:
            _expect("action_dim", int(self.manifest["action_dim"]), int(expected_action_dim))
        if expected_transition_steps is not None:
            _expect(
                "transition_steps",
                int(self.manifest["transition_steps"]),
                int(expected_transition_steps),
            )
        if expected_latent_channels is not None:
            _expect(
                "latent_channels",
                int(self.manifest["latent_channels"]),
                int(expected_latent_channels),
            )

        self._by_dataset_index: dict[int, dict[str, Any]] = {}
        self.rows_by_episode: dict[str, list[dict[str, Any]]] = defaultdict(list)
        self.task_by_episode: dict[str, str] = {}
        for row in self.rows:
            dataset_index = int(row["dataset_index"])
            if dataset_index in self._by_dataset_index:
                raise ValueError(f"duplicate latent-cache dataset_index={dataset_index}")
            self._by_dataset_index[dataset_index] = row
            episode_id = str(row["episode_id"])
            task_id = str(row["task_id"])
            self.rows_by_episode[episode_id].append(row)
            previous = self.task_by_episode.setdefault(episode_id, task_id)
            if previous != task_id:
                raise ValueError(
                    f"latent cache episode {episode_id} mixes semantic tasks: "
                    f"{previous!r} vs {task_id!r}"
                )
        for episode_rows in self.rows_by_episode.values():
            episode_rows.sort(key=lambda item: int(item["episode_step"]))

        self.training_index = tuple(
            CTETrainIndex(
                dataset_index=int(row["dataset_index"]),
                episode_id=str(row["episode_id"]),
                task_id=str(row["task_id"]),
                episode_step=int(row["episode_step"]),
            )
            for row in self.rows
        )

        # mmap handles are process-local and opened lazily, which is safe when
        # this Dataset is copied into DataLoader workers.
        self._rank_arrays: dict[int, dict[str, np.ndarray]] = {}

    def validate_storage_layout(self, *, require_complete_windows: bool = False) -> dict[str, int]:
        """Validate every rank mmap header and all index rank/offset references.

        This is intentionally cheap: ``np.load(..., mmap_mode="r")`` reads array
        headers without materializing the 67 GiB payload.  Boolean validity arrays
        are small enough to scan when ``require_complete_windows=True``.
        """
        rows_by_rank: dict[int, list[dict[str, Any]]] = defaultdict(list)
        for row in self.rows:
            rows_by_rank[int(row["rank"])].append(row)

        seen_slots: set[tuple[int, int]] = set()
        total_slots = 0
        expected_t, expected_c, expected_h, expected_w = self.latent_shape
        transition_steps = int(self.manifest["transition_steps"])
        action_dim = int(self.manifest["action_dim"])

        for rank, rank_rows in sorted(rows_by_rank.items()):
            arrays = self._arrays(rank)
            latents = arrays["latents"]
            actions = arrays["actions"]
            frame_valid = arrays["frame_valid"]
            transition_valid = arrays["transition_valid"]
            n = int(latents.shape[0])

            if latents.dtype != np.uint16 or tuple(latents.shape[1:]) != self.latent_shape:
                raise ValueError(
                    f"rank {rank} latent mmap mismatch: dtype={latents.dtype}, "
                    f"shape={latents.shape}, expected=[N,{expected_t},{expected_c},{expected_h},{expected_w}] uint16"
                )
            expected_action_shape = (n, expected_t - 1, transition_steps, action_dim)
            if tuple(actions.shape) != expected_action_shape:
                raise ValueError(
                    f"rank {rank} action mmap shape mismatch: got={actions.shape}, "
                    f"expected={expected_action_shape}"
                )
            if tuple(frame_valid.shape) != (n, expected_t):
                raise ValueError(
                    f"rank {rank} frame_valid shape mismatch: {frame_valid.shape}"
                )
            if tuple(transition_valid.shape) != (n, expected_t - 1, transition_steps):
                raise ValueError(
                    f"rank {rank} transition_valid shape mismatch: {transition_valid.shape}"
                )
            if actions.dtype != np.float32:
                raise ValueError(
                    f"rank {rank} transition_actions must be float32 to preserve Stage-1 precision, got {actions.dtype}"
                )

            for row in rank_rows:
                offset = int(row["offset"])
                if offset < 0 or offset >= n:
                    raise ValueError(
                        f"latent cache row offset out of range: rank={rank}, offset={offset}, size={n}"
                    )
                slot = (rank, offset)
                if slot in seen_slots:
                    raise ValueError(f"duplicate latent cache rank/offset slot: {slot}")
                seen_slots.add(slot)
            total_slots += len(rank_rows)

            if require_complete_windows:
                # Phase/effect cache-v4 uses all-ones masks.  Refuse to silently
                # turn a padded Stage-1 source window into a valid full-prefix step.
                if not bool(np.asarray(frame_valid, dtype=np.bool_).all()):
                    raise ValueError(f"rank {rank} latent cache contains invalid/padded frame boundaries")
                if not bool(np.asarray(transition_valid, dtype=np.bool_).all()):
                    raise ValueError(f"rank {rank} latent cache contains invalid/padded transitions")

        if total_slots != len(self.rows):
            raise RuntimeError(
                f"latent cache storage validation counted {total_slots} rows, expected {len(self.rows)}"
            )
        return {"rows": len(self.rows), "ranks": len(rows_by_rank)}

    def __len__(self) -> int:
        return len(self.rows)

    def _arrays(self, rank: int) -> dict[str, np.ndarray]:
        arrays = self._rank_arrays.get(rank)
        if arrays is not None:
            return arrays
        rank_dir = self.root / f"rank_{rank:03d}"
        required = {
            "latents": rank_dir / "latents_bf16_u16.npy",
            "actions": rank_dir / "transition_actions.npy",
            "frame_valid": rank_dir / "frame_valid.npy",
            "transition_valid": rank_dir / "transition_valid.npy",
        }
        missing = [str(path) for path in required.values() if not path.is_file()]
        if missing:
            raise FileNotFoundError(f"latent cache rank {rank} is incomplete: {missing}")
        arrays = {
            name: np.load(path, mmap_mode="r")
            for name, path in required.items()
        }
        self._rank_arrays[rank] = arrays
        return arrays

    def row_for_dataset_index(self, dataset_index: int) -> dict[str, Any]:
        try:
            return self._by_dataset_index[int(dataset_index)]
        except KeyError as exc:
            raise IndexError(
                f"latent cache has no Stage-1 window for dataset_index={dataset_index}"
            ) from exc

    def get_row(self, row: dict[str, Any]) -> dict[str, Any]:
        rank = int(row["rank"])
        offset = int(row["offset"])
        arrays = self._arrays(rank)

        latent = u16_numpy_to_bf16_tensor(arrays["latents"][offset])
        actions = torch.from_numpy(np.array(arrays["actions"][offset], copy=True)).float()
        frame_valid = torch.from_numpy(
            np.array(arrays["frame_valid"][offset], copy=True, dtype=np.uint8)
        ).bool()
        transition_valid = torch.from_numpy(
            np.array(arrays["transition_valid"][offset], copy=True, dtype=np.uint8)
        ).bool()

        episode_id = str(row["episode_id"])
        episode_step = int(row["episode_step"])
        task_id = str(row["task_id"])
        return {
            "dataset_index": int(row["dataset_index"]),
            "cte_frames": latent,
            "transition_actions": actions,
            "frame_valid": frame_valid,
            "transition_valid": transition_valid,
            "task_id": task_id,
            "task_name": task_id,
            "episode_id": episode_id,
            "episode_step": episode_step,
            "episode": EpisodeMetadata(
                episode_id=episode_id,
                task_id=task_id,
                task_name=task_id,
                instruction="",
                episode_step=episode_step,
                episode_num_steps=0,
                attempt_id=0,
            ),
        }

    def __getitem__(self, dataset_index: int) -> dict[str, Any]:
        return self.get_row(self.row_for_dataset_index(int(dataset_index)))
