"""Memory-mapped Stage-1 CTE latent cache reader.

This module reads the cache generated by ``scripts/precompute_zeva_cte_latents.py``.
Latents are stored as the raw uint16 bit-pattern of torch.bfloat16 values so
loading does not introduce a numerical conversion.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import torch
from torch.utils.data import Dataset

from fastwam.datasets.zeva_r…,
            "episode_step": episode_step,
                        "episode": EpisodeMetadata(
                                        episode_id=episode_id,
                                                        task_id=task_id,
                                                                        task_name=task_id,
                                                                                        instruction="",
                                                                                                        episode_step=episode_step,
                                                                                                                        episode_num_steps=0,
                                                                                                                                        attempt_id=0,
                                                                                                                                                    ),
                                                                                                                                                            }
                                                                                                                                                            
                                                                                                                                                                def __getitem__(self, dataset_index: int) -> dict[str, Any]:
                                                                                                                                                                        return self.get_row(self.row_for_dataset_index(int(dataset_index)))
                                                                                                                                                                        """